### ISSUE TITLE
Doesn't detect annotation

### ISSUE THREAD

**Issue by mholleville** [GoogleCloudPlatform/gke-managed-certs#34]
Hi ! 

I'm trying to use gke-managed-certs. I following the documentation and when I deploy the controller I have this log

`attempting to acquire leader lease  kube-system/managed-certificate-controller...`

Is it normal ?

**Comment by krzykwas** [comment]
It is normal.

**Comment by mholleville** [comment]
When I bind my cert I have this following log 

`Operation cannot be fulfilled on managedcertificates.networking.gke.io "test.com": the object has been modified; please apply your changes to the latest version and try again`

When I show my ingress I have two cert ! Is it normal for a second certificate to be added automatically?

**Comment by krzykwas** [comment]
I don't know the exact steps you have made. The error you have pasted means that the GKE Managed Certificates controller tried to make a change to a ManagedCertificate resource. It failed, probably because of another change that has been made in the meantime. This is fine, the controller will retry in a moment.

A single ManagedCertificate resource attached to Ingress should only result in creating and attaching a single SslCertificate resource via Ingress annotation pre-shared-cert. It would help to see the yaml definitions of the resources you have created.

**Comment by krzykwas** [comment]
I'm closing this issue, but please let me know if you'd like to reopen it.
